// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mohaymen_sTask.DataAccess;

#nullable disable

namespace Mohaymen_sTask.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mohaymen_sTask.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            Password = "12345",
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true,
                            Password = "12345",
                            UserName = "User"
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = true,
                            Password = "6789",
                            UserName = "Mahsa"
                        },
                        new
                        {
                            Id = 4,
                            IsAvailable = false,
                            Password = "98765",
                            UserName = "Mahya"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
